<%@ Page Title="" Language="C#" MasterPageFile="~/Site1.Master" AutoEventWireup="true" CodeBehind="Ticket.aspx.cs" Inherits="Lab3.TicketPage" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">


    <asp:Table ID="Table2" runat="server" HorizontalAlign="Left">
        <asp:TableRow>
            <asp:TableCell>
                <asp:GridView ID="grdTickets" runat="server" 
                    DataSourceID="dtasrcServiceTicketID" 
                    DataKeyNames="ServiceTicketID" 
                    AutoGenerateSelectButton="true" 
                    AllowSorting="true" 
                    AutoGenerateColumns="false" 
                    OnSelectedIndexChanged="grdTickets_SelectedIndexChanged">
                </asp:GridView>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:DetailsView ID="dtlVwTicketNotes" runat="server" Height="50px" Width="250px"
                    AllowPaging="true"
                    DataKeyNames="NoteID"
                    AutoGeneratedRows="false" 
                    AutoGenerateEditButton="true" 
                    OnModeChanging="dtlVwTicketNotes_ModeChanging" 
                    DataSourceID="dtasrcNotes">
                    <Fields>
                        <asp:BoundField HeaderText="NoteTitle" DataField="NoteTitle"/>
                        <asp:BoundField HeaderText="NoteContent" DataField="NoteContent" />
                    </Fields>
                    </asp:DetailsView>             
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>

    <asp:Table ID="Table1" runat="server" Height="100px">
        <asp:TableRow>
            <asp:TableCell>
                <asp:DropDownList ID="ddlEmployee" runat="server"
                    AutoPostBack ="true"
                    DataSourceID="dtasrcEmployee"
                    DataTextField="NamePosition"
                    DataValueField="EmployeeID"
                    Visible="false">
                </asp:DropDownList>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Button ID="btnEmployeeCancel" runat="server" Text="Cancel" OnClick="btnEmployeeCancel_Click" Visible="false" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="btnEmployeeSave" runat="server" Text="Save" OnClick="btnEmployeeSave_Click" Visible="false" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="lblErrorMsg" runat="server" Text=""></asp:Label>
            </asp:TableCell>
        </asp:TableRow>
    </asp:Table>

    <asp:Table ID="tblBtns" runat="server" HorizontalAlign="Left">
        <asp:TableRow>
            <asp:TableCell>
                <asp:Button ID="btnAddNote" runat="server" Text="Add Note:" OnClick="btnAddNote_Click" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="btnAssignEmployee" runat="server" Text="Assign Employee" OnClick="btnAssignEmployee_Click" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="btnCompleteTicket" runat="server" Text="Complete Ticket" OnClick="btnCompleteTicket_Click" />
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="lblNoteTitle" runat="server" Text="Note Title:" Visible="false"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="txtNoteTitle" runat="server" Visible="false"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Label ID="lblNoteContent" runat="server" Text="Note Content:" Visible="false"></asp:Label>
            </asp:TableCell>
            <asp:TableCell>
                <asp:TextBox ID="txtNoteContent" runat="server" Height="300px" Width="300px" TextMode="MultiLine" Visible="false"></asp:TextBox>
            </asp:TableCell>
        </asp:TableRow>
        <asp:TableRow>
            <asp:TableCell>
                <asp:Button ID="btnNoteCancel" runat="server" Text="Cancel" OnClick="btnNoteCancel_Click" Visible="false" />
            </asp:TableCell>
            <asp:TableCell>
                <asp:Button ID="btnNoteSave" runat="server" Text="Save Note" OnClick="btnNoteSave_Click" Visible="false"/>
            </asp:TableCell>
        </asp:TableRow>
       <asp:TableRow>
           <asp:TableCell>
               <asp:Label ID="lblNoteErrorMsg" runat="server" Text=""></asp:Label>
           </asp:TableCell>
       </asp:TableRow>
    </asp:Table>



    <asp:SqlDataSource ID="dtasrcServiceTicketID" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Lab3 %>" >
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="dtasrcNotes" runat="server" 
        ConnectionString="<%$ ConnectionStrings:Lab3 %>" 
        SelectCommand="SELECT * FROM Notes WHERE ServiceTicketID = @ServiceTicketID" 
        UpdateCommand="UPDATE Notes SET NoteTitle=@NoteTitle, NoteContent=@NoteContent WHERE NoteID=@NoteID">
        <SelectParameters>
            <asp:ControlParameter name="ServiceTicketID" ControlID="grdTickets"/>
        </SelectParameters>
        <UpdateParameters>
            <asp:Parameter type="String" Name="NoteTitle"/>
            <asp:Parameter Type="String" Name="NoteContent"/>
        </UpdateParameters>
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="dtasrcEmployee" runat="server"
        ConnectionString="<%$ ConnectionStrings:Lab3 %>"
        SelectCommand="SELECT EmployeeID, FirstName + ' ' + LastName + ' ' + Position AS NamePosition FROM Employee">
    </asp:SqlDataSource>



</asp:Content>
